# Generated by Django 5.2 on 2025-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weatherdata_wind_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('trek', 'Trek'), ('heritage', 'Heritage Site'), ('park', 'National Park'), ('cultural', 'cultural'), ('wildlife', 'wildlife'), ('leisure', 'leisure')], max_length=20),
        ),
    ]
