# Generated by Django 5.2 on 2025-05-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
    ]
