# Generated by Django 5.2 on 2025-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apikey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
